from __future__ import annotations

import random
from dataclasses import dataclass
from typing import Any, Optional

import numpy as np

from modules.workforce_engine.schemas import ProblemSetup, WorkforceState


ACTION_SPACE_SIZE = 55

MODALITY_ACTION_START = 0
MODALITY_ACTION_END = 2

ENTRY_HOUR_ACTION_START = 3
ENTRY_HOUR_ACTION_END = 26

DAY_OFF_ACTION_START = 27
DAY_OFF_ACTION_END = 54

MODALITIES = [4, 6, 8]
MODALITY_TO_INDEX = {4: 0, 6: 1, 8: 2}
MODALITY_TO_ACTION_ID = {4: 0, 6: 1, 8: 2}
ACTION_ID_TO_MODALITY = {0: 4, 1: 6, 2: 8}

HOURS_PER_DAY = 24
DAYS_PER_WEEK = 7
WEEKS = 4
DAYS_IN_HORIZON = 28

DAY_OFF_ACTION_MATRIX = np.array(
    [
        [0, 1, 2, 3, 4, 5, 6],
        [1, 7, 8, 9, 10, 11, 12],
        [2, 8, 13, 14, 15, 16, 17],
        [3, 9, 14, 18, 19, 20, 21],
        [4, 10, 15, 19, 22, 23, 24],
        [5, 11, 16, 20, 23, 25, 26],
        [6, 12, 17, 21, 24, 26, 27],
    ],
    dtype=int,
)


def _build_day_off_action_to_pair() -> dict[int, tuple[int, int]]:
    mapping: dict[int, tuple[int, int]] = {}
    for row in range(DAYS_PER_WEEK):
        for col in range(row, DAYS_PER_WEEK):
            internal_id = int(DAY_OFF_ACTION_MATRIX[row, col])
            mapping[internal_id] = (row, col)
    return mapping


DAY_OFF_ACTION_TO_PAIR = _build_day_off_action_to_pair()


@dataclass(frozen=True)
class _StateSnapshot:
    """Internal state metadata stored before an action is applied."""

    coverage_before: np.ndarray
    remaining_stock: np.ndarray
    expansion_mode: bool
    current_modality: Optional[int]
    current_entry_hour: Optional[int]
    assignment_week: int


@dataclass(frozen=True)
class _PlannedStep:
    """Internal action record used before final demand is known."""

    snapshot: _StateSnapshot
    action_id: int
    legal_action_ids: list[int]


class DemandSimulator:
    """
    Constructive coverage simulator aligned with WorkforceEngine/MCTS.

    The simulator generates a positive trajectory from a synthetic feasible plan.
    First, it builds the final accumulated coverage matrix C_final. That matrix is
    then interpreted as the perfect initial demand. For every action step t, the
    stored WorkforceState is reconstructed as:

        residual_demand_t = C_final - C_t

    where C_t is the accumulated coverage before action t.

    Output trajectory format matches the MCTS training sample convention:

        {
            "state": WorkforceState,
            "policy": np.ndarray shape (55,),
            "action_id": int,
            "reward": 1.0,
        }

    The policy is uniform over the legal actions for that state and zero for
    illegal actions. The reward is always 1.0 because the generated trajectory
    covers exactly the demand defined by its own final coverage matrix.
    """

    def __init__(self, problem_setup: ProblemSetup, seed: Optional[int] = None):
        self.problem_setup = problem_setup
        self.seed = seed
        self.rng = random.Random(seed)

        self.entry_hours = self._resolve_entry_hours(problem_setup)
        self.closing_hour = problem_setup.closing_hour
        self.fixed_day_off = problem_setup.fixed_day_off
        self.mobile_days_off_count = problem_setup.mobile_days_off_count

        self._validate_setup()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def compute_coverage(
        self,
        mod_4: int,
        mod_6: int,
        mod_8: int,
    ) -> tuple[np.ndarray, list[dict[str, Any]]]:
        """
        Generate final coverage matrix and a positive MCTS-compatible trajectory.

        Parameters
        ----------
        mod_4, mod_6, mod_8:
            Number of generated resources for each modality. These values are
            also used as the initial stock in the reconstructed WorkforceState.

        Returns
        -------
        coverage_matrix:
            Final accumulated coverage C_final, shape (24, 28). This is the
            perfect demand matrix generated by the simulator.

        trajectory:
            List of training samples with WorkforceState, policy, action_id and
            reward=1.0.
        """
        self._validate_resource_inputs(mod_4, mod_6, mod_8)

        initial_stock = np.array([mod_4, mod_6, mod_8], dtype=int)
        if int(initial_stock.sum()) <= 0:
            raise ValueError("At least one resource is required to generate coverage.")

        resources = self._build_resources_list(mod_4, mod_6, mod_8)
        coverage_matrix, planned_steps = self._generate_plan(resources, initial_stock)

        if coverage_matrix.sum() <= 0:
            raise ValueError("Generated coverage is empty; cannot build WorkforceState.")

        trajectory = self._build_mcts_trajectory(
            final_coverage=coverage_matrix,
            planned_steps=planned_steps,
        )
        return coverage_matrix, trajectory

    # ------------------------------------------------------------------
    # Setup validation
    # ------------------------------------------------------------------

    @staticmethod
    def _resolve_entry_hours(problem_setup: ProblemSetup) -> list[int]:
        if hasattr(problem_setup, "get_allowed_entry_hours"):
            return list(problem_setup.get_allowed_entry_hours())
        allowed_entry_hours = getattr(problem_setup, "allowed_entry_hours", None)
        if allowed_entry_hours is None:
            return list(range(HOURS_PER_DAY))
        return list(allowed_entry_hours)

    def _validate_setup(self) -> None:
        if not isinstance(self.entry_hours, list) or len(self.entry_hours) == 0:
            raise ValueError("allowed_entry_hours must resolve to a non-empty list.")
        if any(not isinstance(h, int) or h < 0 or h > 23 for h in self.entry_hours):
            raise ValueError("allowed_entry_hours must contain integers between 0 and 23.")
        if len(set(self.entry_hours)) != len(self.entry_hours):
            raise ValueError("allowed_entry_hours must not contain duplicated values.")
        if self.closing_hour is not None and (
            not isinstance(self.closing_hour, int)
            or self.closing_hour < 0
            or self.closing_hour > 23
        ):
            raise ValueError("closing_hour must be an integer between 0 and 23 or None.")
        if self.fixed_day_off is not None and (
            not isinstance(self.fixed_day_off, int)
            or self.fixed_day_off < 0
            or self.fixed_day_off > 6
        ):
            raise ValueError("fixed_day_off must be an integer between 0 and 6 or None.")
        if self.mobile_days_off_count not in (0, 1, 2):
            raise ValueError("mobile_days_off_count must be 0, 1 or 2.")
        fixed_count = 1 if self.fixed_day_off is not None else 0
        if fixed_count + self.mobile_days_off_count > 2:
            raise ValueError("Total days off cannot exceed 2.")

    @staticmethod
    def _validate_resource_inputs(mod_4: int, mod_6: int, mod_8: int) -> None:
        for name, value in {"mod_4": mod_4, "mod_6": mod_6, "mod_8": mod_8}.items():
            if not isinstance(value, int) or value < 0:
                raise ValueError(f"{name} must be an integer >= 0.")

    # ------------------------------------------------------------------
    # Plan generation
    # ------------------------------------------------------------------

    def _build_resources_list(self, mod_4: int, mod_6: int, mod_8: int) -> list[int]:
        resources = [4] * mod_4 + [6] * mod_6 + [8] * mod_8
        self.rng.shuffle(resources)
        return resources

    def _generate_plan(
        self,
        resources: list[int],
        initial_stock: np.ndarray,
    ) -> tuple[np.ndarray, list[_PlannedStep]]:
        """
        Generate actions and coverage snapshots before knowing final demand.
        """
        coverage = np.zeros((HOURS_PER_DAY, DAYS_IN_HORIZON), dtype=int)
        planned_steps: list[_PlannedStep] = []
        closed_resources = np.zeros(3, dtype=int)

        for modality in resources:
            current_modality: Optional[int] = None
            current_entry_hour: Optional[int] = None
            assignment_week = 0

            # State before selecting modality.
            remaining_stock = initial_stock - closed_resources
            expansion_mode = self._compute_expansion_mode(
                remaining_stock=remaining_stock,
                current_modality=current_modality,
                current_entry_hour=current_entry_hour,
                assignment_week=assignment_week,
            )
            modality_snapshot = self._make_snapshot(
                coverage_before=coverage,
                remaining_stock=remaining_stock,
                expansion_mode=expansion_mode,
                current_modality=current_modality,
                current_entry_hour=current_entry_hour,
                assignment_week=assignment_week,
            )
            modality_legal_actions = self._legal_modality_action_ids(remaining_stock, expansion_mode)
            modality_action_id = self._modality_action_id(modality)
            if modality_action_id not in modality_legal_actions:
                raise ValueError("Generated modality action is not legal for current stock.")
            planned_steps.append(
                _PlannedStep(
                    snapshot=modality_snapshot,
                    action_id=modality_action_id,
                    legal_action_ids=modality_legal_actions,
                )
            )
            current_modality = modality

            for week in range(WEEKS):
                assignment_week = week
                current_entry_hour = None
                remaining_stock = initial_stock - closed_resources
                expansion_mode = self._compute_expansion_mode(
                    remaining_stock=remaining_stock,
                    current_modality=current_modality,
                    current_entry_hour=current_entry_hour,
                    assignment_week=assignment_week,
                )

                entry_legal_actions = self._legal_entry_hour_action_ids(
                    current_modality=current_modality,
                    assignment_week=assignment_week,
                )
                if not entry_legal_actions:
                    raise ValueError(
                        f"No legal entry actions for modality={current_modality}, week={assignment_week}."
                    )
                entry_action_id = self.rng.choice(entry_legal_actions)
                entry_hour = self._entry_hour_from_action_id(entry_action_id)

                entry_snapshot = self._make_snapshot(
                    coverage_before=coverage,
                    remaining_stock=remaining_stock,
                    expansion_mode=expansion_mode,
                    current_modality=current_modality,
                    current_entry_hour=current_entry_hour,
                    assignment_week=assignment_week,
                )
                planned_steps.append(
                    _PlannedStep(
                        snapshot=entry_snapshot,
                        action_id=entry_action_id,
                        legal_action_ids=entry_legal_actions,
                    )
                )
                current_entry_hour = entry_hour

                if self.mobile_days_off_count > 0:
                    remaining_stock = initial_stock - closed_resources
                    expansion_mode = self._compute_expansion_mode(
                        remaining_stock=remaining_stock,
                        current_modality=current_modality,
                        current_entry_hour=current_entry_hour,
                        assignment_week=assignment_week,
                    )
                    day_off_legal_actions = self._legal_day_off_action_ids_for_context(
                        current_modality=current_modality,
                        current_entry_hour=current_entry_hour,
                        assignment_week=assignment_week,
                    )
                    if not day_off_legal_actions:
                        raise ValueError(
                            f"No legal day-off actions for modality={current_modality}, "
                            f"entry_hour={current_entry_hour}, week={assignment_week}."
                        )
                    day_off_action_id = self.rng.choice(day_off_legal_actions)
                    days_off = self.decode_day_off_action(day_off_action_id)

                    day_off_snapshot = self._make_snapshot(
                        coverage_before=coverage,
                        remaining_stock=remaining_stock,
                        expansion_mode=expansion_mode,
                        current_modality=current_modality,
                        current_entry_hour=current_entry_hour,
                        assignment_week=assignment_week,
                    )
                    planned_steps.append(
                        _PlannedStep(
                            snapshot=day_off_snapshot,
                            action_id=day_off_action_id,
                            legal_action_ids=day_off_legal_actions,
                        )
                    )
                else:
                    days_off = self._get_days_off_without_mobile_action()

                weekly_coverage = self._build_weekly_coverage(
                    modality=current_modality,
                    week=assignment_week,
                    entry_hour=current_entry_hour,
                    days_off=days_off,
                )
                coverage = coverage + weekly_coverage

            closed_resources[MODALITY_TO_INDEX[modality]] += 1

        return coverage, planned_steps

    @staticmethod
    def _make_snapshot(
        coverage_before: np.ndarray,
        remaining_stock: np.ndarray,
        expansion_mode: bool,
        current_modality: Optional[int],
        current_entry_hour: Optional[int],
        assignment_week: int,
    ) -> _StateSnapshot:
        return _StateSnapshot(
            coverage_before=coverage_before.copy(),
            remaining_stock=remaining_stock.copy(),
            expansion_mode=expansion_mode,
            current_modality=current_modality,
            current_entry_hour=current_entry_hour,
            assignment_week=assignment_week,
        )

    @staticmethod
    def _compute_expansion_mode(
        remaining_stock: np.ndarray,
        current_modality: Optional[int],
        current_entry_hour: Optional[int],
        assignment_week: int,
    ) -> bool:
        no_resource_in_progress = (
            current_modality is None
            and current_entry_hour is None
            and assignment_week == 0
        )
        return bool(no_resource_in_progress and np.all(remaining_stock == 0))

    # ------------------------------------------------------------------
    # Trajectory reconstruction
    # ------------------------------------------------------------------

    def _build_mcts_trajectory(
        self,
        final_coverage: np.ndarray,
        planned_steps: list[_PlannedStep],
    ) -> list[dict[str, Any]]:
        initial_demand_total = int(final_coverage.sum())
        if initial_demand_total <= 0:
            raise ValueError("final_coverage must have positive total demand.")

        trajectory: list[dict[str, Any]] = []

        for planned_step in planned_steps:
            snapshot = planned_step.snapshot
            residual_demand = final_coverage - snapshot.coverage_before
            state = WorkforceState(
                residual_demand=residual_demand.astype(int),
                remaining_stock=snapshot.remaining_stock.astype(int),
                expansion_mode=snapshot.expansion_mode,
                current_modality=snapshot.current_modality,
                current_entry_hour=snapshot.current_entry_hour,
                assignment_week=snapshot.assignment_week,
                initial_demand_total=initial_demand_total,
            )

            policy = self._uniform_policy_over_legal_actions(planned_step.legal_action_ids)

            trajectory.append(
                {
                    "state": state,
                    "policy": policy,
                    "action_id": planned_step.action_id,
                    "reward": 1.0,
                }
            )

        return trajectory

    @staticmethod
    def _uniform_policy_over_legal_actions(legal_action_ids: list[int]) -> np.ndarray:
        if len(legal_action_ids) == 0:
            raise ValueError("At least one legal action is required.")
        policy = np.zeros(ACTION_SPACE_SIZE, dtype=float)
        policy[legal_action_ids] = 1.0 / len(legal_action_ids)
        return policy

    # ------------------------------------------------------------------
    # Legal action helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _legal_modality_action_ids(
        remaining_stock: np.ndarray,
        expansion_mode: bool,
    ) -> list[int]:
        if expansion_mode:
            return [0, 1, 2]
        return [
            MODALITY_TO_ACTION_ID[modality]
            for modality in MODALITIES
            if remaining_stock[MODALITY_TO_INDEX[modality]] > 0
        ]

    def _legal_entry_hour_action_ids(
        self,
        current_modality: int,
        assignment_week: int,
    ) -> list[int]:
        legal_action_ids: list[int] = []
        for hour in self._get_legal_entry_hours_by_closing(current_modality):
            if self.mobile_days_off_count == 0:
                days_off = self._get_days_off_without_mobile_action()
                if not self._weekly_coverage_fits_horizon(
                    week=assignment_week,
                    entry_hour=hour,
                    modality=current_modality,
                    days_off=days_off,
                ):
                    continue
            else:
                has_feasible_day_off = any(
                    self._weekly_coverage_fits_horizon(
                        week=assignment_week,
                        entry_hour=hour,
                        modality=current_modality,
                        days_off=self.decode_day_off_action(day_off_action_id),
                    )
                    for day_off_action_id in self.get_legal_day_off_action_ids()
                )
                if not has_feasible_day_off:
                    continue

            legal_action_ids.append(self._entry_hour_action_id(hour))
        return legal_action_ids

    def _legal_day_off_action_ids_for_context(
        self,
        current_modality: int,
        current_entry_hour: int,
        assignment_week: int,
    ) -> list[int]:
        return [
            action_id
            for action_id in self.get_legal_day_off_action_ids()
            if self._weekly_coverage_fits_horizon(
                week=assignment_week,
                entry_hour=current_entry_hour,
                modality=current_modality,
                days_off=self.decode_day_off_action(action_id),
            )
        ]

    def _get_legal_entry_hours_by_closing(self, modality: int) -> list[int]:
        if modality not in MODALITIES:
            raise ValueError(f"Invalid modality: {modality}")
        if self.closing_hour is None:
            return list(self.entry_hours)
        return [hour for hour in self.entry_hours if hour + modality <= self.closing_hour]

    def get_legal_day_off_action_ids(self) -> list[int]:
        if self.mobile_days_off_count == 0:
            return []

        legal_internal_ids: set[int] = set()

        if self.fixed_day_off is None and self.mobile_days_off_count == 1:
            for day in range(DAYS_PER_WEEK):
                legal_internal_ids.add(int(DAY_OFF_ACTION_MATRIX[day, day]))
        elif self.fixed_day_off is not None and self.mobile_days_off_count == 1:
            fixed_day = self.fixed_day_off
            for mobile_day in range(DAYS_PER_WEEK):
                if mobile_day != fixed_day:
                    legal_internal_ids.add(int(DAY_OFF_ACTION_MATRIX[fixed_day, mobile_day]))
        elif self.fixed_day_off is None and self.mobile_days_off_count == 2:
            for d1 in range(DAYS_PER_WEEK):
                for d2 in range(d1 + 1, DAYS_PER_WEEK):
                    legal_internal_ids.add(int(DAY_OFF_ACTION_MATRIX[d1, d2]))
        else:
            raise ValueError("Unsupported day-off configuration in ProblemSetup.")

        return sorted(DAY_OFF_ACTION_START + internal_id for internal_id in legal_internal_ids)

    # ------------------------------------------------------------------
    # Action encoding/decoding
    # ------------------------------------------------------------------

    @staticmethod
    def _modality_action_id(modality: int) -> int:
        if modality not in MODALITY_TO_ACTION_ID:
            raise ValueError("Modality must be one of 4, 6 or 8.")
        return MODALITY_TO_ACTION_ID[modality]

    @staticmethod
    def _entry_hour_action_id(entry_hour: int) -> int:
        if not isinstance(entry_hour, int) or entry_hour < 0 or entry_hour > 23:
            raise ValueError("entry_hour must be an integer between 0 and 23.")
        return ENTRY_HOUR_ACTION_START + entry_hour

    @staticmethod
    def _entry_hour_from_action_id(action_id: int) -> int:
        if action_id < ENTRY_HOUR_ACTION_START or action_id > ENTRY_HOUR_ACTION_END:
            raise ValueError("action_id does not belong to entry-hour block.")
        return action_id - ENTRY_HOUR_ACTION_START

    def decode_day_off_action(self, action_id: int) -> set[int]:
        if action_id < DAY_OFF_ACTION_START or action_id > DAY_OFF_ACTION_END:
            raise ValueError("action_id does not belong to day-off block.")
        internal_id = action_id - DAY_OFF_ACTION_START
        if internal_id not in DAY_OFF_ACTION_TO_PAIR:
            raise ValueError(f"Invalid internal day-off id: {internal_id}")

        d1, d2 = DAY_OFF_ACTION_TO_PAIR[internal_id]

        if self.fixed_day_off is None:
            if self.mobile_days_off_count == 1:
                return {d1}
            if self.mobile_days_off_count == 2:
                return {d1, d2}
        if self.fixed_day_off is not None and self.mobile_days_off_count == 1:
            return {d1, d2}
        raise ValueError("Day-off action is incompatible with current setup.")

    def _get_days_off_without_mobile_action(self) -> set[int]:
        if self.fixed_day_off is None:
            return set()
        return {self.fixed_day_off}

    # ------------------------------------------------------------------
    # Coverage
    # ------------------------------------------------------------------

    def _weekly_coverage_fits_horizon(
        self,
        week: int,
        entry_hour: int,
        modality: int,
        days_off: set[int],
    ) -> bool:
        week_start_day = week * DAYS_PER_WEEK
        working_days = set(range(DAYS_PER_WEEK)) - set(days_off)
        for relative_day in working_days:
            absolute_day = week_start_day + relative_day
            if self._get_shift_cells(
                absolute_day=absolute_day,
                entry_hour=entry_hour,
                modality=modality,
                validate_only=True,
            ) is None:
                return False
        return True

    def _build_weekly_coverage(
        self,
        modality: int,
        week: int,
        entry_hour: int,
        days_off: set[int],
    ) -> np.ndarray:
        coverage = np.zeros((HOURS_PER_DAY, DAYS_IN_HORIZON), dtype=int)
        week_start_day = week * DAYS_PER_WEEK
        working_days = set(range(DAYS_PER_WEEK)) - set(days_off)

        for relative_day in sorted(working_days):
            absolute_day = week_start_day + relative_day
            cells = self._get_shift_cells(
                absolute_day=absolute_day,
                entry_hour=entry_hour,
                modality=modality,
            )
            if cells is None:
                raise ValueError("Coverage exceeds the 28-day horizon.")
            for hour, day in cells:
                coverage[hour, day] += 1
        return coverage

    @staticmethod
    def _get_shift_cells(
        absolute_day: int,
        entry_hour: int,
        modality: int,
        validate_only: bool = False,
    ) -> Optional[list[tuple[int, int]]]:
        cells: list[tuple[int, int]] = []
        for offset in range(modality):
            raw_hour = entry_hour + offset
            target_day = absolute_day + raw_hour // HOURS_PER_DAY
            target_hour = raw_hour % HOURS_PER_DAY
            if target_day >= DAYS_IN_HORIZON:
                if validate_only:
                    return None
                raise ValueError("Coverage exceeds the 28-day horizon.")
            cells.append((target_hour, target_day))
        return cells
